server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:benjidb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

coincap:
  api:
    url: https://rest.coincap.io/v3
    # ADD YOUR API KEY HERE
    key:
    refresh-rate: 10000
    max-threads: 2